// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StocksInvesthink.Data;

#nullable disable

namespace StocksInvesthink.Migrations
{
    [DbContext(typeof(StocksInvesthinkContext))]
    partial class StocksInvesthinkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("StocksInvesthink.Models.HistoricalPrice", b =>
                {
                    b.Property<int>("HistoricalPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistoricalPriceId");

                    b.HasIndex("UserId", "StockId");

                    b.ToTable("HistoricalPrices");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorInstance", b =>
                {
                    b.Property<int>("IndicatorInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndicatorTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IndicatorInstanceId");

                    b.HasIndex("IndicatorTypeId");

                    b.HasIndex("UserId", "StockId");

                    b.ToTable("IndicatorInstances");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorType", b =>
                {
                    b.Property<int>("IndicatorTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IndicatorTypeId");

                    b.ToTable("IndicatorTypes");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorValue", b =>
                {
                    b.Property<int>("IndicatorValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoricalPriceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndicatorInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("IndicatorValueId");

                    b.HasIndex("HistoricalPriceId");

                    b.HasIndex("IndicatorInstanceId");

                    b.ToTable("IndicatorValues");
                });

            modelBuilder.Entity("StocksInvesthink.Models.Signal", b =>
                {
                    b.Property<int>("SignalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("IndicatorValueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SignalId");

                    b.HasIndex("IndicatorValueId");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("StocksInvesthink.Models.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StocksInvesthink.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StocksInvesthink.Models.UserPreference", b =>
                {
                    b.Property<int>("UserPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultIndicatorTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserPreferenceId");

                    b.HasIndex("DefaultIndicatorTypeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("StocksInvesthink.Models.UserStock", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "StockId");

                    b.HasIndex("StockId");

                    b.ToTable("UserStocks");
                });

            modelBuilder.Entity("StocksInvesthink.Models.HistoricalPrice", b =>
                {
                    b.HasOne("StocksInvesthink.Models.UserStock", "UserStock")
                        .WithMany("HistoricalPrices")
                        .HasForeignKey("UserId", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserStock");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorInstance", b =>
                {
                    b.HasOne("StocksInvesthink.Models.IndicatorType", "IndicatorType")
                        .WithMany("IndicatorInstances")
                        .HasForeignKey("IndicatorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StocksInvesthink.Models.UserStock", "UserStock")
                        .WithMany("IndicatorInstances")
                        .HasForeignKey("UserId", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndicatorType");

                    b.Navigation("UserStock");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorValue", b =>
                {
                    b.HasOne("StocksInvesthink.Models.HistoricalPrice", "HistoricalPrice")
                        .WithMany("IndicatorValues")
                        .HasForeignKey("HistoricalPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StocksInvesthink.Models.IndicatorInstance", "IndicatorInstance")
                        .WithMany("IndicatorValues")
                        .HasForeignKey("IndicatorInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalPrice");

                    b.Navigation("IndicatorInstance");
                });

            modelBuilder.Entity("StocksInvesthink.Models.Signal", b =>
                {
                    b.HasOne("StocksInvesthink.Models.IndicatorValue", "IndicatorValue")
                        .WithMany("Signals")
                        .HasForeignKey("IndicatorValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndicatorValue");
                });

            modelBuilder.Entity("StocksInvesthink.Models.UserPreference", b =>
                {
                    b.HasOne("StocksInvesthink.Models.IndicatorType", "DefaultIndicatorType")
                        .WithMany()
                        .HasForeignKey("DefaultIndicatorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StocksInvesthink.Models.User", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("StocksInvesthink.Models.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultIndicatorType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StocksInvesthink.Models.UserStock", b =>
                {
                    b.HasOne("StocksInvesthink.Models.Stock", "Stock")
                        .WithMany("UserStocks")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StocksInvesthink.Models.User", "User")
                        .WithMany("UserStocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StocksInvesthink.Models.HistoricalPrice", b =>
                {
                    b.Navigation("IndicatorValues");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorInstance", b =>
                {
                    b.Navigation("IndicatorValues");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorType", b =>
                {
                    b.Navigation("IndicatorInstances");
                });

            modelBuilder.Entity("StocksInvesthink.Models.IndicatorValue", b =>
                {
                    b.Navigation("Signals");
                });

            modelBuilder.Entity("StocksInvesthink.Models.Stock", b =>
                {
                    b.Navigation("UserStocks");
                });

            modelBuilder.Entity("StocksInvesthink.Models.User", b =>
                {
                    b.Navigation("UserPreference")
                        .IsRequired();

                    b.Navigation("UserStocks");
                });

            modelBuilder.Entity("StocksInvesthink.Models.UserStock", b =>
                {
                    b.Navigation("HistoricalPrices");

                    b.Navigation("IndicatorInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
